#!/bin/sh
# Start/stop the kaffi daemon.
#
### BEGIN INIT INFO
# Provides:          kaffi
# Required-Start:    $syslog $remote_fs $networking $time
# Required-Stop:     $syslog $remote_fs $networking $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Coffee management
# Description:       Manages dispensing of coffee
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE=/var/run/kaffi.pid

case "$1" in
	start)
		log_daemon_msg "Starting Kaffi service" "kaffi"
		env PYTHON_PATH=/root/kaffi start-stop-daemon --start --pidfile $PIDFILE --startas /root/kaffi/kaffi.py --background --make-pidfile -- --daemon
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping Kaffi service" "kaffi"
		start-stop-daemon --stop --pidfile /var/run/kaffi.pid --retry 10
		log_end_msg $?
		rm -f $PIDFILE
		;;
	restart)
		$0 stop && sleep 1 && $0 start
		;;
esac
